services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\ImportBundle\:
        resource: '../../*'
        exclude: '../../{Model,DependencyInjection,Resources}'
